from TSMaster import *
import sys
blacklist = ["tkinter"] # modules such as tkinter will release GIL by itself, which is not allowed in TSMster Toolbox
for mod in blacklist:
    if sys.modules.get(mod):
        tmp_import = __import__ (mod)
        sys.modules[mod] = None

# Auto Generated Python Code, do not modify START [UI] --------------
class Pedal_Control(frmTSForm):
    def __init__(self):
        # set type name internally
        self.ExternalTypeName = type(self).__name__
        if hasattr(self, "on_before_ui_creation"):
            method = getattr(self, "on_before_ui_creation")
            method()
        try:
            # Form properties
            if not self.IsConfigurationLoaded:
                self.Left = 178
                self.Top = 195
                self.Caption = 'Pedal_Control'
                self.ClientHeight = 502
                self.ClientWidth = 998
            self.Color = clBtnFace
            self.DoubleBuffered = True
            self.Font.Charset = DEFAULT_CHARSET
            self.Font.Color = clWindowText
            self.Font.Height = -12
            self.Font.Name = 'Segoe UI'
            self.Font.Style = []
            self.KeyPreview = True
            self.Position = "poDesigned"
            self.Visible = True
            self.TextHeight = 15
            # Create control: pnlGround = Panel(self)
            self.pnlGround = Panel(self)
            self.pnlGround.Name = "pnlGround"
            self.pnlGround.Parent = self
            self.pnlGround.Left = 0
            self.pnlGround.Top = 0
            self.pnlGround.Width = 998
            self.pnlGround.Height = 502
            self.pnlGround.Cursor = crArrow
            self.pnlGround.Align = "alClient"
            self.pnlGround.Caption = 'pnlGround'
            self.pnlGround.ParentBackground = False
            self.pnlGround.ShowCaption = "False"
            self.pnlGround.TabOrder = 0
            # Create control: pnlTop = Panel(self)
            self.pnlTop = Panel(self)
            self.pnlTop.Name = "pnlTop"
            self.pnlTop.Parent = self.pnlGround
            self.pnlTop.Left = 1
            self.pnlTop.Top = 1
            self.pnlTop.Width = 996
            self.pnlTop.Height = 50
            self.pnlTop.Cursor = crArrow
            self.pnlTop.Align = "alTop"
            self.pnlTop.Caption = 'pnlTop'
            self.pnlTop.Color = clWhite
            self.pnlTop.ParentBackground = False
            self.pnlTop.ShowCaption = "False"
            self.pnlTop.TabOrder = 0
            # Create control: svgbtnStart = TSSvgImageButton(self)
            self.svgbtnStart = TSSvgImageButton(self)
            self.svgbtnStart.Name = "svgbtnStart"
            self.svgbtnStart.Parent = self.pnlTop
            self.svgbtnStart.Left = 13
            self.svgbtnStart.Top = 0
            self.svgbtnStart.Width = 70
            self.svgbtnStart.Height = 46
            self.svgbtnStart.Cursor = crArrow
            self.svgbtnStart.Caption = 'Start'
            self.svgbtnStart.TabOrder = 0
            self.svgbtnStart.VerticalAlignment = "taAlignBottom"
            self.svgbtnStart.SvgFileName = 'D:/Projects/TigerTe/Projects/2023-12_TigerTE_Hardware/res/tio_servo_start.svg'
            self.svgbtnStart.SvgFileContent = 'PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/PjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+PHN2ZyB0PSIxNjMxMTczNzUzOTI1IiBjbGFzcz0iaWNvbiIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHAtaWQ9IjM3Njk0IiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgd2lkdGg9IjEyOCIgaGVpZ2h0PSIxMjgiPjxkZWZzPjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+PC9zdHlsZT48L2RlZnM+PHBhdGggZD0iTTUxMiA1MTJtLTUxMiAwYTUxMiA1MTIgMCAxIDAgMTAyNCAwIDUxMiA1MTIgMCAxIDAtMTAyNCAwWiIgZmlsbD0iIzEyOTZkYiIgcC1pZD0iMzc2OTUiIGRhdGEtc3BtLWFuY2hvci1pZD0iYTMxM3guNzc4MTA2OS4wLmk0NCIgY2xhc3M9InNlbGVjdGVkIj48L3BhdGg+PHBhdGggZD0iTTY5MS45NjggNTkxLjIwNjRsLTEyMy45MDQtNjMuMzg1NmEzNy40Nzg0IDM3LjQ3ODQgMCAwIDAtMTQuNzQ1Ni0zLjA3Mkg1MzIuNDhWMzU2LjUwNTZhNDEuNDcyIDQxLjQ3MiAwIDAgMC00MS4wMTEyLTQyLjA4NjQgNDEuNDcyIDQxLjQ3MiAwIDAgMC00MC45NiA0Mi4wODY0djMwMS4xNTg0bC05My42OTYtMjAuMTcyOGMtMi4yMDE2LTAuMjU2LTQuMDk2LTAuODcwNC02LjUwMjQtMC44NzA0YTMwLjAwMzIgMzAuMDAzMiAwIDAgMC0yMS41NTUyIDkuMzE4NEwzMDcuMiA2NjguMzEzNmwxMzQuODYwOCAxMzguNDk2QTQwLjY1MjggNDAuNjUyOCAwIDAgMCA0NzEuMDQgODE5LjJoMTg1LjM0NGMyMC40OCAwIDM2LjM1Mi0xNS40NjI0IDM5LjM3MjgtMzUuODRsMjAuNDgtMTQ3Ljg2NTZjMC4yNTYtMS45NDU2IDAuNTYzMi0zLjg5MTIgMC41NjMyLTUuNTI5NmE0Mi4wODY0IDQyLjA4NjQgMCAwIDAtMjQuODMyLTM4Ljc1ODRNNDIzLjI3MDQgNDYxLjMxMlYzNTYuNTU2OGMwLTM4LjcwNzIgMzAuNjE3Ni03MC4wOTI4IDY4LjI0OTYtNzAuMDkyOHM2OC4yNDk2IDMxLjM4NTYgNjguMjQ5NiA3MC4wOTI4djEwNC44NTc2YTEyNi43MiAxMjYuNzIgMCAwIDAgNTQuNTc5Mi0xMDQuODU3NkM2MTQuNCAyODYuNzIgNTU5LjUxMzYgMjMwLjQgNDkxLjUyIDIzMC40Yy02Ny45NDI0IDAtMTIyLjc3NzYgNTYuMzItMTIyLjc3NzYgMTI2LjE1NjggMCA0My43MjQ4IDIxLjUwNCA4Mi4xNzYgNTQuNTc5MiAxMDQuODU3NiIgZmlsbD0iI0ZGRkZGRiIgcC1pZD0iMzc2OTYiPjwvcGF0aD48L3N2Zz4NCg__'
            self.svgbtnStart.ImageIndex = -1
            self.svgbtnStart.ImageStretch = False
            self.svgbtnStart.ReadOnly = False
            # Create control: TSSvgImageButton2 = TSSvgImageButton(self)
            self.TSSvgImageButton2 = TSSvgImageButton(self)
            self.TSSvgImageButton2.Name = "TSSvgImageButton2"
            self.TSSvgImageButton2.Parent = self.pnlTop
            self.TSSvgImageButton2.Left = 102
            self.TSSvgImageButton2.Top = 0
            self.TSSvgImageButton2.Width = 71
            self.TSSvgImageButton2.Height = 46
            self.TSSvgImageButton2.Cursor = crArrow
            self.TSSvgImageButton2.Caption = 'Start'
            self.TSSvgImageButton2.TabOrder = 1
            self.TSSvgImageButton2.VerticalAlignment = "taAlignBottom"
            self.TSSvgImageButton2.SvgFileName = 'D:/Projects/TigerTe/Projects/2023-12_TigerTE_Hardware/res/tio_servo_stop.svg'
            self.TSSvgImageButton2.SvgFileContent = 'PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/PjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+PHN2ZyB0PSIxNjMxMTc0MzE3MDU4IiBjbGFzcz0iaWNvbiIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHAtaWQ9Ijc4MTQ4IiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgd2lkdGg9IjEyOCIgaGVpZ2h0PSIxMjgiPjxkZWZzPjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+PC9zdHlsZT48L2RlZnM+PHBhdGggZD0iTTY2Ny44ODY5MzMgMzk4LjQzODRoLTMxMS43NzM4NjZhNDUuNzcyOCA0NS43NzI4IDAgMSAxIDAtOTEuNTc5NzMzaDMxMS43NzM4NjZhNDUuODA2OTMzIDQ1LjgwNjkzMyAwIDAgMSAwIDkxLjU3OTczM00wIDUxMmMwIDI4Mi43NjA1MzMgMjI5LjIzOTQ2NyA1MTIgNTEyIDUxMiA1Ny4yNzU3MzMgMCAxMTIuMjk4NjY3LTkuNTU3MzMzIDE2My43MDM0NjctMjYuODk3MDY3LTMuNzU0NjY3LTUuMDE3Ni02MS41NDI0LTE3Ni45ODEzMzMtNzUuOTEyNTM0LTIyMS40OTEyLTE0LjM3MDEzMy00NC41MDk4NjcgMTYuNjU3MDY3LTczLjI1MDEzMyAzNy40NDQyNjctODQuMDM2MjY2IDIwLjgyMTMzMy0xMC43ODYxMzMgNjEuNzgxMzMzLTEwLjc4NjEzMyA3OC4xNjUzMzMgOC44MDY0bC0wLjE3MDY2Ni0xNTEuMjQ0OGMwLTAuODUzMzMzIDAuMDY4MjY3LTEuNzA2NjY3IDAuMTcwNjY2LTIuNTk0MTM0IDUuMzI0OC0zOS45MzYgMjkuNjI3NzMzLTYyLjcwMjkzMyA2OC4xOTg0LTYyLjcwMjkzM3M2Mi44Mzk0NjcgMjIuNzY2OTMzIDY4LjE2NDI2NyA2Mi43MDI5MzNjMC4xMDI0IDAuODUzMzMzIDAuMTcwNjY3IDEuNzA2NjY3IDAuMTcwNjY3IDIuNTk0MTM0djE3Ny4zNTY4bDExNy44MjgyNjYgMTQuNzc5NzMzQTUwOS42Nzg5MzMgNTA5LjY3ODkzMyAwIDAgMCAxMDI0IDUxMmMwLTI4Mi43NjA1MzMtMjI5LjIzOTQ2Ny01MTItNTEyLTUxMkMyMjkuMjM5NDY3IDAgMCAyMjkuMjM5NDY3IDAgNTEyeiIgZmlsbD0iI2Q4MWUwNiIgcC1pZD0iNzgxNDkiIGRhdGEtc3BtLWFuY2hvci1pZD0iYTMxM3guNzc4MTA2OS4wLmk1NSIgY2xhc3M9InNlbGVjdGVkIj48L3BhdGg+PHBhdGggZD0iTTc1NC4yNzg0IDc3OS45NDY2NjdjMCAyMS4yOTkyLTI5LjI1MjI2NyAyNy4yMDQyNjctMzcuNTQ2NjY3IDcuNTc3Ni0xMS43NzYtMTkuNDkwMTMzLTIxLjE2MjY2Ny0zNC4wOTkyLTI4LjIyODI2Ni00My43OTMwNjctMTAuNTgxMzMzLTE0LjU0MDgtMjAuMDM2MjY3LTE4LjQ2NjEzMy0zMy43NTc4NjctMTIuNjI5MzMzLTEzLjY4NzQ2NyA1Ljg3MDkzMy0xOC41MzQ0IDE2LjQ1MjI2Ny0xNC4yNjc3MzMgMzEuOTQ4OCA0LjI2NjY2NyAxNS40OTY1MzMgNTAuODU4NjY3IDE3OC43MjIxMzMgNjAuODI1NiAyMDAuOTQyOTMzIDcuMTY4IDE1LjkwNjEzMyAxNi4wNDI2NjcgMjEuMTk2OCAzMC43ODgyNjYgMTkuMTgyOTMzYTIwLjgyMTMzMyAyMC44MjEzMzMgMCAwIDEgMi42NjI0LTAuMjA0OGgxNzcuMDE1NDY3YzAuMzQxMzMzIDAgMS4xMjY0IDAgMi4xODQ1MzMtMC4wNjgyNjZhMjA2LjQ3MjUzMyAyMDYuNDcyNTMzIDAgMCAwIDE2LjM4NC0xLjcwNjY2N2M0LjUzOTczMy0wLjY4MjY2NyA4LjY2OTg2Ny0xLjQzMzYgMTIuMDgzMi0yLjI4NjkzMyAyLjY2MjQtMC42ODI2NjcgNC42NzYyNjctMS4zMzEyIDUuNzM0NC0xLjc3NDkzNGExNS4yNTc2IDE1LjI1NzYgMCAwIDAgMS43MDY2NjctMi45Njk2IDc0LjQxMDY2NyA3NC40MTA2NjcgMCAwIDAgNS4wMTc2LTE4LjM2MzczM2wyNi44NjI5MzMtMTI4LjE3MDY2N2ExNy44MTc2IDE3LjgxNzYgMCAwIDEgMC41MTItMS45Nzk3MzNjNS42MzItMTcuNTEwNCA1LjYzMi0yOC4yMjgyNjcgMi42NjI0LTMyLjQyNjY2Ny00LjMzNDkzMy02LjE0NC0xMS4wMjUwNjctMTAuNTgxMzMzLTIwLjgyMTMzMy0xMy4zMTJsLTEzNC4xNDQtMTYuNzkzNmExOS41MjQyNjcgMTkuNTI0MjY3IDAgMCAxLTE3LjA2NjY2Ny0xOS4zODc3MzN2LTE4My4xMjUzMzNjLTIuOTY5Ni0yMC4xMzg2NjctMTEuMjY0LTI3LjYxMzg2Ny0yOS4yODY0LTI3LjYxMzg2Ny0xOC4wNTY1MzMgMC0yNi4zNTA5MzMgNy40NDEwNjctMjkuMzIwNTMzIDI3LjYxMzg2N3YyMTkuMzQwOHoiIGZpbGw9IiNkODFlMDYiIHAtaWQ9Ijc4MTUwIiBkYXRhLXNwbS1hbmNob3ItaWQ9ImEzMTN4Ljc3ODEwNjkuMC5pNTYiIGNsYXNzPSJzZWxlY3RlZCI+PC9wYXRoPjwvc3ZnPg0K'
            self.TSSvgImageButton2.ImageIndex = -1
            self.TSSvgImageButton2.ImageStretch = False
            self.TSSvgImageButton2.ReadOnly = False
            # Create control: TSSvgImageButton3 = TSSvgImageButton(self)
            self.TSSvgImageButton3 = TSSvgImageButton(self)
            self.TSSvgImageButton3.Name = "TSSvgImageButton3"
            self.TSSvgImageButton3.Parent = self.pnlTop
            self.TSSvgImageButton3.Left = 186
            self.TSSvgImageButton3.Top = 0
            self.TSSvgImageButton3.Width = 70
            self.TSSvgImageButton3.Height = 45
            self.TSSvgImageButton3.Cursor = crArrow
            self.TSSvgImageButton3.Caption = 'Start'
            self.TSSvgImageButton3.TabOrder = 2
            self.TSSvgImageButton3.VerticalAlignment = "taAlignBottom"
            self.TSSvgImageButton3.SvgFileName = 'D:/Projects/TigerTe/Projects/2023-12_TigerTE_Hardware/res/tio_servo_init.svg'
            self.TSSvgImageButton3.SvgFileContent = 'PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/PjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+PHN2ZyB0PSIxNjMyMzg4NjM0NzczIiBjbGFzcz0iaWNvbiIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHAtaWQ9IjU4NzQiIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iMTI4IiBoZWlnaHQ9IjEyOCI+PGRlZnM+PHN0eWxlIHR5cGU9InRleHQvY3NzIj48L3N0eWxlPjwvZGVmcz48cGF0aCBkPSJNNTEzLjAxMiA2MS45NzljLTI0NS4zNi0wLjQ4NS00NTAuMzg3IDIwMS44ODEtNDUxLjAxIDQ0NS4xNTctMC42NDIgMjUwLjUyIDE5OS44ODEgNDU0LjA2NyA0NDguMTI3IDQ1NC44ODQgMjQ1LjkwNyAwLjgwOSA0NTIuMjg0LTIwNC4wMDggNDUxLjg3MS00NDguNDU1LTAuNDE5LTI0Ny4wODgtMjAzLjI1Ny00NTEuMS00NDguOTg4LTQ1MS41ODZ6IG0xMzEuMjQxIDYwMi45MThjLTM2LjY4NSAxMC43NzMtNzEuNjU4LTAuMTczLTEwMy4yOTYtMTYuOTkzLTIwLjkyOC0xMS4xMjYtMzEuNTA2LTUuODM5LTQ2LjExNSA5LjIzMi01OC45NDIgNjAuODA2LTEyMC4xOTEgMTE5LjQwMi0xNzguMzQzIDE4MC45MzUtMTguNjM1IDE5LjcxOS0zMC44MTIgMTguOTctNTAuMTcyIDMuMjY5LTMyLjI0NC0yNi4xNTEtNjAuODY1LTU1LjI0NS04Ni41MzktODcuODM3LTEzLjA2OC0xNi41ODktMTMuMzI5LTI2LjgwMiAyLjgxNi00Mi40MzlDMjQ1Ljc3MyA2NDkuODg3IDMwNi44NzYgNTg2LjU4MSAzNjkuNjYzIDUyNWMxMi45MzQtMTIuNjg2IDE0LjkxMi0yMS40MjggNi4zOS0zOC40NzQtNDAuMzU5LTgwLjcyNi0yMi45NTItMTQyLjczOSA1MS45MTItMTkzLjQwOSA0Ni42MzMtMzEuNTYyIDk3LjcxLTUxLjA4NCAxNTQuMTUyLTU0LjczOCAxMi42NTEtMC44MTkgMjYuMjYyLTIuNDMyIDQwLjUxMyA4LjkwOC0zMS41MzYgMzEuNTE1LTYxLjYwOSA2MS4xNTItOTEuMTk4IDkxLjI2My0yNi41MTQgMjYuOTgyLTI2LjkzMiA0MS45NzctMC43MTMgNjkuMDI1IDI5LjQ2OCAzMC40MDEgNTkuOTc3IDU5Ljc5MSA4OS45NjMgODkuNjkyIDIxLjEwNyAyMS4wNDcgNDEuNjA3IDIwLjA0NSA2MS44NzMtMS4yMjMgMzAuNTc0LTMyLjA4NSA2MS4yMjgtNjQuMDk0IDkxLjY0Mi05NS45MTkgNS4xOTUgNC43NjcgNi40NTkgNS4zNjEgNi43MjkgNi4yNTUgMjUuNDQgODQuMjIyLTUzLjQyNSAyMzQuMDctMTM2LjY3MyAyNTguNTE3eiIgZmlsbD0iIzEyOTZkYiIgcC1pZD0iNTg3NSI+PC9wYXRoPjwvc3ZnPg0K'
            self.TSSvgImageButton3.ImageIndex = -1
            self.TSSvgImageButton3.ImageStretch = False
            self.TSSvgImageButton3.ReadOnly = False
            # Create control: TSSvgImageButton4 = TSSvgImageButton(self)
            self.TSSvgImageButton4 = TSSvgImageButton(self)
            self.TSSvgImageButton4.Name = "TSSvgImageButton4"
            self.TSSvgImageButton4.Parent = self.pnlTop
            self.TSSvgImageButton4.Left = 288
            self.TSSvgImageButton4.Top = 0
            self.TSSvgImageButton4.Width = 70
            self.TSSvgImageButton4.Height = 45
            self.TSSvgImageButton4.Cursor = crArrow
            self.TSSvgImageButton4.Caption = 'Start'
            self.TSSvgImageButton4.TabOrder = 3
            self.TSSvgImageButton4.VerticalAlignment = "taAlignBottom"
            self.TSSvgImageButton4.SvgFileName = 'D:/Projects/TigerTe/Projects/2023-12_TigerTE_Hardware/res/tio_servo_jog_in.svg'
            self.TSSvgImageButton4.SvgFileContent = 'PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/PjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+PHN2ZyB0PSIxNjMyMzg0MTYyMjY3IiBjbGFzcz0iaWNvbiIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHAtaWQ9IjMzOTIiIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iMTI4IiBoZWlnaHQ9IjEyOCI+PGRlZnM+PHN0eWxlIHR5cGU9InRleHQvY3NzIj48L3N0eWxlPjwvZGVmcz48cGF0aCBkPSJNNTk3LjMzMzMzMyA4NS4zMzMzMzN2ODUzLjMzMzMzNGg0Mi42NjY2NjdjNDcuMDE4NjY3IDAgODUuMzMzMzMzLTM4LjMxNDY2NyA4NS4zMzMzMzMtODUuMzMzMzM0di0yMTMuMzMzMzMzaDIxMy4zMzMzMzRWMzg0aC0yMTMuMzMzMzM0VjE3MC42NjY2NjdjMC00Ny4wMTg2NjctMzguMzE0NjY3LTg1LjMzMzMzMy04NS4zMzMzMzMtODUuMzMzMzM0ek0yNTYgMzg0bC0xNzAuNjY2NjY3IDEyOCAxNzAuNjY2NjY3IDEyOHYtODUuMzMzMzMzaDI1NnYtODUuMzMzMzM0SDI1NnoiIGZpbGw9IiMxMjk2ZGIiIHAtaWQ9IjMzOTMiPjwvcGF0aD48L3N2Zz4NCg__'
            self.TSSvgImageButton4.ImageIndex = -1
            self.TSSvgImageButton4.ImageStretch = False
            self.TSSvgImageButton4.ReadOnly = False
            # Create control: TSSvgImageButton5 = TSSvgImageButton(self)
            self.TSSvgImageButton5 = TSSvgImageButton(self)
            self.TSSvgImageButton5.Name = "TSSvgImageButton5"
            self.TSSvgImageButton5.Parent = self.pnlTop
            self.TSSvgImageButton5.Left = 358
            self.TSSvgImageButton5.Top = 0
            self.TSSvgImageButton5.Width = 71
            self.TSSvgImageButton5.Height = 45
            self.TSSvgImageButton5.Cursor = crArrow
            self.TSSvgImageButton5.Caption = 'Start'
            self.TSSvgImageButton5.TabOrder = 4
            self.TSSvgImageButton5.VerticalAlignment = "taAlignBottom"
            self.TSSvgImageButton5.SvgFileName = 'D:/Projects/TigerTe/Projects/2023-12_TigerTE_Hardware/res/tio_servo_jog_out.svg'
            self.TSSvgImageButton5.SvgFileContent = 'PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/PjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+PHN2ZyB0PSIxNjMyMzg0MTY5NTExIiBjbGFzcz0iaWNvbiIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHAtaWQ9IjM1ODciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iMTI4IiBoZWlnaHQ9IjEyOCI+PGRlZnM+PHN0eWxlIHR5cGU9InRleHQvY3NzIj48L3N0eWxlPjwvZGVmcz48cGF0aCBkPSJNMzg0IDg1LjMzMzMzM2MtNDcuMDE4NjY3IDAtODUuMzMzMzMzIDM4LjMxNDY2Ny04NS4zMzMzMzMgODUuMzMzMzM0djIxMy4zMzMzMzNIODUuMzMzMzMzdjI1NmgyMTMuMzMzMzM0djIxMy4zMzMzMzNjMCA0Ny4wMTg2NjcgMzguMzE0NjY3IDg1LjMzMzMzMyA4NS4zMzMzMzMgODUuMzMzMzM0aDQyLjY2NjY2N1Y4NS4zMzMzMzN6IG0zODQgMjk4LjY2NjY2N3Y4NS4zMzMzMzNoLTI1NnY4NS4zMzMzMzRoMjU2djg1LjMzMzMzM2wxNzAuNjY2NjY3LTEyOHoiIGZpbGw9IiMxMjk2ZGIiIHAtaWQ9IjM1ODgiPjwvcGF0aD48L3N2Zz4NCg__'
            self.TSSvgImageButton5.ImageIndex = -1
            self.TSSvgImageButton5.ImageStretch = False
            self.TSSvgImageButton5.ReadOnly = False
            # Create control: TSSvgImageButton6 = TSSvgImageButton(self)
            self.TSSvgImageButton6 = TSSvgImageButton(self)
            self.TSSvgImageButton6.Name = "TSSvgImageButton6"
            self.TSSvgImageButton6.Parent = self.pnlTop
            self.TSSvgImageButton6.Left = 429
            self.TSSvgImageButton6.Top = 0
            self.TSSvgImageButton6.Width = 70
            self.TSSvgImageButton6.Height = 45
            self.TSSvgImageButton6.Cursor = crArrow
            self.TSSvgImageButton6.Caption = 'Start'
            self.TSSvgImageButton6.TabOrder = 5
            self.TSSvgImageButton6.VerticalAlignment = "taAlignBottom"
            self.TSSvgImageButton6.SvgFileName = 'D:/Projects/TigerTe/Projects/2023-12_TigerTE_Hardware/res/tio_servo_set_zero.svg'
            self.TSSvgImageButton6.SvgFileContent = 'PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/PjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+PHN2ZyB0PSIxNjMxNDQ5NDA1MTMxIiBjbGFzcz0iaWNvbiIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHAtaWQ9IjMxMjkzIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgd2lkdGg9IjEyOCIgaGVpZ2h0PSIxMjgiPjxkZWZzPjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+PC9zdHlsZT48L2RlZnM+PHBhdGggZD0iTTgzNi4yNjY2NjcgMEgxODcuNzMzMzMzQTE4Ny43MzMzMzMgMTg3LjczMzMzMyAwIDAgMCAwIDE4Ny43MzMzMzN2NjQ4LjUzMzMzNGExODcuNzMzMzMzIDE4Ny43MzMzMzMgMCAwIDAgMTg3LjczMzMzMyAxODcuNzMzMzMzaDY0OC41MzMzMzRhMTg3LjczMzMzMyAxODcuNzMzMzMzIDAgMCAwIDE4Ny43MzMzMzMtMTg3LjczMzMzM1YxODcuNzMzMzMzQTE4Ny43MzMzMzMgMTg3LjczMzMzMyAwIDAgMCA4MzYuMjY2NjY3IDB6IG04NS4zMzMzMzMgODM2LjI2NjY2N2E4NS4zMzMzMzMgODUuMzMzMzMzIDAgMCAxLTg1LjMzMzMzMyA4NS4zMzMzMzNIMTg3LjczMzMzM2E4NS4zMzMzMzMgODUuMzMzMzMzIDAgMCAxLTg1LjMzMzMzMy04NS4zMzMzMzNWMTg3LjczMzMzM2E4NS4zMzMzMzMgODUuMzMzMzMzIDAgMCAxIDg1LjMzMzMzMy04NS4zMzMzMzNoNjQ4LjUzMzMzNGE4NS4zMzMzMzMgODUuMzMzMzMzIDAgMCAxIDg1LjMzMzMzMyA4NS4zMzMzMzN6IiBmaWxsPSIjMTI5NmRiIiBwLWlkPSIzMTI5NCI+PC9wYXRoPjxwYXRoIGQ9Ik01MTcuOTczMzMzIDI1NnE5MS4xMzYgMCAxNDcuMjg1MzM0IDgzLjYyNjY2N2EzMTguMjkzMzMzIDMxOC4yOTMzMzMgMCAwIDEgNTEuMiAxODEuOTMwNjY2IDI4MS4yNTg2NjcgMjgxLjI1ODY2NyAwIDAgMS00OS40OTMzMzQgMTcwLjY2NjY2N0ExODAuMjI0IDE4MC4yMjQgMCAwIDEgNTEyIDc2OGExNzkuNTQxMzMzIDE3OS41NDEzMzMgMCAwIDEtMTUzLjYtNzkuNzAxMzMzIDI5MC4xMzMzMzMgMjkwLjEzMzMzMyAwIDAgMS01MS4yLTE3NC41OTIgMjkyLjAxMDY2NyAyOTIuMDEwNjY3IDAgMCAxIDUyLjkwNjY2Ny0xNzcuMzIyNjY3QTE4NC42NjEzMzMgMTg0LjY2MTMzMyAwIDAgMSA1MTcuOTczMzMzIDI1NnpNNTEyIDM2Ny40NDUzMzNhNzUuOTQ2NjY3IDc1Ljk0NjY2NyAwIDAgMC02OC4yNjY2NjcgNDYuMDggMjExLjk2OCAyMTEuOTY4IDAgMCAwLTIyLjM1NzMzMyAxMDEuMzc2QTIxMC43NzMzMzMgMjEwLjc3MzMzMyAwIDAgMCA0NDMuNzMzMzMzIDYxNS43NjUzMzNhNzcuODI0IDc3LjgyNCAwIDAgMCA2OS40NjEzMzQgNDUuNTY4cTM5Ljc2NTMzMyAwIDY0LTQ4LjEyOGEyMzAuOTEyIDIzMC45MTIgMCAwIDAgMjEuODQ1MzMzLTEwNC4xMDY2NjYgMjAyLjA2OTMzMyAyMDIuMDY5MzMzIDAgMCAwLTIxLjE2MjY2Ny05Ny42MjEzMzRBNzIuODc0NjY3IDcyLjg3NDY2NyAwIDAgMCA1MTIgMzY3LjQ0NTMzM3oiIGZpbGw9IiMxMjk2ZGIiIHAtaWQ9IjMxMjk1Ij48L3BhdGg+PC9zdmc+DQo_'
            self.TSSvgImageButton6.ImageIndex = -1
            self.TSSvgImageButton6.ImageStretch = False
            self.TSSvgImageButton6.ReadOnly = False
            # Create control: TSSvgImageButton7 = TSSvgImageButton(self)
            self.TSSvgImageButton7 = TSSvgImageButton(self)
            self.TSSvgImageButton7.Name = "TSSvgImageButton7"
            self.TSSvgImageButton7.Parent = self.pnlTop
            self.TSSvgImageButton7.Left = 499
            self.TSSvgImageButton7.Top = 0
            self.TSSvgImageButton7.Width = 71
            self.TSSvgImageButton7.Height = 45
            self.TSSvgImageButton7.Cursor = crArrow
            self.TSSvgImageButton7.Caption = 'Start'
            self.TSSvgImageButton7.TabOrder = 6
            self.TSSvgImageButton7.VerticalAlignment = "taAlignBottom"
            self.TSSvgImageButton7.SvgFileName = 'D:/Projects/TigerTe/Projects/2023-12_TigerTE_Hardware/res/tio_servo_exhaust.svg'
            self.TSSvgImageButton7.SvgFileContent = 'PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/PjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+PHN2ZyB0PSIxNjQ5NDEwNTA3NzgxIiBjbGFzcz0iaWNvbiIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHAtaWQ9IjU5NzYiIGRhdGEtZGFya3JlYWRlci1pbmxpbmUtZmlsbD0iIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiPjxkZWZzPjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+QGZvbnQtZmFjZSB7IGZvbnQtZmFtaWx5OiBmZWVkYmFjay1pY29uZm9udDsgc3JjOiB1cmwoIi8vYXQuYWxpY2RuLmNvbS90L2ZvbnRfMTAzMTE1OF91Njl3OHloeGR1LndvZmYyP3Q9MTYzMDAzMzc1OTk0NCIpIGZvcm1hdCgid29mZjIiKSwgdXJsKCIvL2F0LmFsaWNkbi5jb20vdC9mb250XzEwMzExNThfdTY5dzh5aHhkdS53b2ZmP3Q9MTYzMDAzMzc1OTk0NCIpIGZvcm1hdCgid29mZiIpLCB1cmwoIi8vYXQuYWxpY2RuLmNvbS90L2ZvbnRfMTAzMTE1OF91Njl3OHloeGR1LnR0Zj90PTE2MzAwMzM3NTk5NDQiKSBmb3JtYXQoInRydWV0eXBlIik7IH0NCjwvc3R5bGU+PC9kZWZzPjxwYXRoIGQ9Ik0xNjAgMjg4SDEyOFY5NmgzMnYzMmgzMmExMjggMTI4IDAgMCAxIDEyOCAxMjh2MzUySDE5MlYyODhjMC0zMiAwLTMyLTMyLTMydjMyeiBtNTEyIDYwOGg2NHYzMmgtNjR2LTMyeiBtOTYgMGg2NHYzMmgtNjR2LTMyeiBtOTYgMGg2NHYzMmgtNjR2LTMyeiBtMC02NGgzMnYzMmgtMTkydi0zMmgzMnYtMjg4aDEyOHYyODh6TTQxNiA0MTZoMTI4djI3MmExNzYgMTc2IDAgMCAxLTM1MiAwdi00OC41MTJoMTMxLjcxMnY1MC4zNjhhNDYuMTQ0IDQ2LjE0NCAwIDAgMCA5Mi4yODggMFY0MTZ6IG0zMiAyNzMuODU2YTc4LjE0NCA3OC4xNDQgMCAxIDEtMTU2LjI4OCAwdi0xOC4zNjhIMjI0djE2LjUxMmExNDQgMTQ0IDAgMSAwIDI4OCAwVjQ0OGgtNjR2MjQxLjg1NnpNNzM2IDM4NHYtMzJjMC0zMiAwLTMyLTMyLTMyaC0xMjhjLTMyIDAtMzIgMC0zMiAzMnYzMmgtMTI4di02NGExMjggMTI4IDAgMCAxIDEyOC0xMjhoMTkyYTEyOCAxMjggMCAwIDEgMTI4IDEyOHY2NGgtMTI4eiBtOTYtMzJ2LTMyYTk2IDk2IDAgMCAwLTk2LTk2aC0xOTJhOTYgOTYgMCAwIDAtOTYgOTZ2MzJoNjRjMC00OS42NjQgMTQuMzM2LTY0IDY0LTY0aDEyOGM0OS42NjQgMCA2NCAxNC4zMzYgNjQgNjRoNjR6IG0tMTI4IDY0aDE5MnY5NmgtMTkydi05NnogbTMyIDMydjMyaDEyOHYtMzJoLTEyOHogbTMyIDEyOHYyNTZoNjR2LTI1NmgtNjR6TTI4OCAyNTZhOTYgOTYgMCAwIDAtOTYtOTZIMTYwdjY0aDMyYTMyIDMyIDAgMCAxIDMyIDMydjMyMGg2NFYyNTZ6IiBwLWlkPSI1OTc3IiBmaWxsPSIjMTI5NmRiIiBkYXRhLWRhcmtyZWFkZXItaW5saW5lLWZpbGw9IiIgc3R5bGU9Ii0tZGFya3JlYWRlci1pbmxpbmUtZmlsbDojMGU3OGFmOyI+PC9wYXRoPjwvc3ZnPg0K'
            self.TSSvgImageButton7.ImageIndex = -1
            self.TSSvgImageButton7.ImageStretch = False
            self.TSSvgImageButton7.ReadOnly = False
            # Create control: pnlCenter = Panel(self)
            self.pnlCenter = Panel(self)
            self.pnlCenter.Name = "pnlCenter"
            self.pnlCenter.Parent = self.pnlGround
            self.pnlCenter.Left = 1
            self.pnlCenter.Top = 51
            self.pnlCenter.Width = 996
            self.pnlCenter.Height = 243
            self.pnlCenter.Cursor = crArrow
            self.pnlCenter.Align = "alTop"
            self.pnlCenter.Caption = 'pnlCenter'
            self.pnlCenter.ShowCaption = "False"
            self.pnlCenter.TabOrder = 1
            # Create control: LabeledEdit2 = LabeledEdit(self)
            self.LabeledEdit2 = LabeledEdit(self)
            self.LabeledEdit2.Name = "LabeledEdit2"
            self.LabeledEdit2.Parent = self.pnlCenter
            self.LabeledEdit2.Left = 19
            self.LabeledEdit2.Top = 45
            self.LabeledEdit2.Width = 136
            self.LabeledEdit2.Height = 30
            self.LabeledEdit2.Cursor = crArrow
            self.LabeledEdit2.TabStop = False
            self.LabeledEdit2.Alignment = "taRightJustify"
            self.LabeledEdit2.Color = 4210752
            self.LabeledEdit2.EditLabel.Width = 105
            self.LabeledEdit2.EditLabel.Height = 15
            self.LabeledEdit2.EditLabel.Caption = 'Pedal Position(mm)'
            self.LabeledEdit2.Font.Charset = DEFAULT_CHARSET
            self.LabeledEdit2.Font.Color = clLime
            self.LabeledEdit2.Font.Height = -18
            self.LabeledEdit2.Font.Name = 'Consolas'
            self.LabeledEdit2.Font.Style = ["fsBold"]
            self.LabeledEdit2.NumbersOnly = True
            self.LabeledEdit2.ParentFont = False
            self.LabeledEdit2.ReadOnly = True
            self.LabeledEdit2.TabOrder = 0
            self.LabeledEdit2.Text = '10.00'
            # Create control: LabeledEdit3 = LabeledEdit(self)
            self.LabeledEdit3 = LabeledEdit(self)
            self.LabeledEdit3.Name = "LabeledEdit3"
            self.LabeledEdit3.Parent = self.pnlCenter
            self.LabeledEdit3.Left = 198
            self.LabeledEdit3.Top = 45
            self.LabeledEdit3.Width = 136
            self.LabeledEdit3.Height = 30
            self.LabeledEdit3.Cursor = crArrow
            self.LabeledEdit3.TabStop = False
            self.LabeledEdit3.Alignment = "taRightJustify"
            self.LabeledEdit3.Color = 4210752
            self.LabeledEdit3.EditLabel.Width = 104
            self.LabeledEdit3.EditLabel.Height = 15
            self.LabeledEdit3.EditLabel.Caption = 'Pedal Speed(mm/s)'
            self.LabeledEdit3.Font.Charset = DEFAULT_CHARSET
            self.LabeledEdit3.Font.Color = clLime
            self.LabeledEdit3.Font.Height = -18
            self.LabeledEdit3.Font.Name = 'Consolas'
            self.LabeledEdit3.Font.Style = ["fsBold"]
            self.LabeledEdit3.NumbersOnly = True
            self.LabeledEdit3.ParentFont = False
            self.LabeledEdit3.ReadOnly = True
            self.LabeledEdit3.TabOrder = 1
            self.LabeledEdit3.Text = '10.00'
            # Create control: LabeledEdit4 = LabeledEdit(self)
            self.LabeledEdit4 = LabeledEdit(self)
            self.LabeledEdit4.Name = "LabeledEdit4"
            self.LabeledEdit4.Parent = self.pnlCenter
            self.LabeledEdit4.Left = 390
            self.LabeledEdit4.Top = 45
            self.LabeledEdit4.Width = 136
            self.LabeledEdit4.Height = 30
            self.LabeledEdit4.Cursor = crArrow
            self.LabeledEdit4.TabStop = False
            self.LabeledEdit4.Alignment = "taRightJustify"
            self.LabeledEdit4.Color = 4210752
            self.LabeledEdit4.EditLabel.Width = 91
            self.LabeledEdit4.EditLabel.Height = 15
            self.LabeledEdit4.EditLabel.Caption = 'MC Pressure(bar)'
            self.LabeledEdit4.Font.Charset = DEFAULT_CHARSET
            self.LabeledEdit4.Font.Color = clLime
            self.LabeledEdit4.Font.Height = -18
            self.LabeledEdit4.Font.Name = 'Consolas'
            self.LabeledEdit4.Font.Style = ["fsBold"]
            self.LabeledEdit4.NumbersOnly = True
            self.LabeledEdit4.ParentFont = False
            self.LabeledEdit4.ReadOnly = True
            self.LabeledEdit4.TabOrder = 2
            self.LabeledEdit4.Text = '10.00'
            # Create control: LabeledEdit5 = LabeledEdit(self)
            self.LabeledEdit5 = LabeledEdit(self)
            self.LabeledEdit5.Name = "LabeledEdit5"
            self.LabeledEdit5.Parent = self.pnlCenter
            self.LabeledEdit5.Left = 390
            self.LabeledEdit5.Top = 122
            self.LabeledEdit5.Width = 128
            self.LabeledEdit5.Height = 23
            self.LabeledEdit5.Cursor = crArrow
            self.LabeledEdit5.EditLabel.Width = 81
            self.LabeledEdit5.EditLabel.Height = 15
            self.LabeledEdit5.EditLabel.Caption = 'Target Force(N)'
            self.LabeledEdit5.TabOrder = 3
            self.LabeledEdit5.Text = 'LabeledEdit5'
            # Create control: LabeledEdit6 = LabeledEdit(self)
            self.LabeledEdit6 = LabeledEdit(self)
            self.LabeledEdit6.Name = "LabeledEdit6"
            self.LabeledEdit6.Parent = self.pnlCenter
            self.LabeledEdit6.Left = 570
            self.LabeledEdit6.Top = 45
            self.LabeledEdit6.Width = 136
            self.LabeledEdit6.Height = 30
            self.LabeledEdit6.Cursor = crArrow
            self.LabeledEdit6.TabStop = False
            self.LabeledEdit6.Alignment = "taRightJustify"
            self.LabeledEdit6.Color = 4210752
            self.LabeledEdit6.EditLabel.Width = 103
            self.LabeledEdit6.EditLabel.Height = 15
            self.LabeledEdit6.EditLabel.Caption = 'Calibrated Force(N)'
            self.LabeledEdit6.Font.Charset = DEFAULT_CHARSET
            self.LabeledEdit6.Font.Color = clLime
            self.LabeledEdit6.Font.Height = -18
            self.LabeledEdit6.Font.Name = 'Consolas'
            self.LabeledEdit6.Font.Style = ["fsBold"]
            self.LabeledEdit6.NumbersOnly = True
            self.LabeledEdit6.ParentFont = False
            self.LabeledEdit6.ReadOnly = True
            self.LabeledEdit6.TabOrder = 4
            self.LabeledEdit6.Text = '10.00'
            # Create control: LabeledEdit7 = LabeledEdit(self)
            self.LabeledEdit7 = LabeledEdit(self)
            self.LabeledEdit7.Name = "LabeledEdit7"
            self.LabeledEdit7.Parent = self.pnlCenter
            self.LabeledEdit7.Left = 198
            self.LabeledEdit7.Top = 122
            self.LabeledEdit7.Width = 128
            self.LabeledEdit7.Height = 23
            self.LabeledEdit7.Cursor = crArrow
            self.LabeledEdit7.EditLabel.Width = 108
            self.LabeledEdit7.EditLabel.Height = 15
            self.LabeledEdit7.EditLabel.Caption = 'Target Position(mm)'
            self.LabeledEdit7.TabOrder = 5
            self.LabeledEdit7.Text = 'LabeledEdit5'
            # Create control: LabeledEdit8 = LabeledEdit(self)
            self.LabeledEdit8 = LabeledEdit(self)
            self.LabeledEdit8.Name = "LabeledEdit8"
            self.LabeledEdit8.Parent = self.pnlCenter
            self.LabeledEdit8.Left = 13
            self.LabeledEdit8.Top = 122
            self.LabeledEdit8.Width = 128
            self.LabeledEdit8.Height = 23
            self.LabeledEdit8.Cursor = crArrow
            self.LabeledEdit8.EditLabel.Width = 107
            self.LabeledEdit8.EditLabel.Height = 15
            self.LabeledEdit8.EditLabel.Caption = 'Target Speed(mm/s)'
            self.LabeledEdit8.TabOrder = 6
            self.LabeledEdit8.Text = 'LabeledEdit5'
            # Create control: Button1 = Button(self)
            self.Button1 = Button(self)
            self.Button1.Name = "Button1"
            self.Button1.Parent = self.pnlCenter
            self.Button1.Left = 13
            self.Button1.Top = 186
            self.Button1.Width = 134
            self.Button1.Height = 32
            self.Button1.Cursor = crArrow
            self.Button1.Caption = 'Goto Target Force'
            self.Button1.ImageIndex = 20
            self.Button1.Images = app.get_system_imagelist_16px()
            self.Button1.TabOrder = 7
            # Create control: Button2 = Button(self)
            self.Button2 = Button(self)
            self.Button2.Name = "Button2"
            self.Button2.Parent = self.pnlCenter
            self.Button2.Left = 198
            self.Button2.Top = 186
            self.Button2.Width = 141
            self.Button2.Height = 32
            self.Button2.Cursor = crArrow
            self.Button2.Caption = 'Goto Target Position'
            self.Button2.ImageIndex = 20
            self.Button2.Images = app.get_system_imagelist_16px()
            self.Button2.TabOrder = 8
            # Create control: Button3 = Button(self)
            self.Button3 = Button(self)
            self.Button3.Name = "Button3"
            self.Button3.Parent = self.pnlCenter
            self.Button3.Left = 390
            self.Button3.Top = 186
            self.Button3.Width = 141
            self.Button3.Height = 32
            self.Button3.Cursor = crArrow
            self.Button3.Caption = 'Go Home'
            self.Button3.ImageIndex = 20
            self.Button3.Images = app.get_system_imagelist_16px()
            self.Button3.TabOrder = 9
            # Create control: LabeledEdit9 = LabeledEdit(self)
            self.LabeledEdit9 = LabeledEdit(self)
            self.LabeledEdit9.Name = "LabeledEdit9"
            self.LabeledEdit9.Parent = self.pnlCenter
            self.LabeledEdit9.Left = 717
            self.LabeledEdit9.Top = 115
            self.LabeledEdit9.Width = 128
            self.LabeledEdit9.Height = 23
            self.LabeledEdit9.Cursor = crArrow
            self.LabeledEdit9.EditLabel.Width = 131
            self.LabeledEdit9.EditLabel.Height = 15
            self.LabeledEdit9.EditLabel.Caption = 'Pedal Max Position(mm)'
            self.LabeledEdit9.TabOrder = 10
            self.LabeledEdit9.Text = 'LabeledEdit5'
            # Create control: LabeledEdit10 = LabeledEdit(self)
            self.LabeledEdit10 = LabeledEdit(self)
            self.LabeledEdit10.Name = "LabeledEdit10"
            self.LabeledEdit10.Parent = self.pnlCenter
            self.LabeledEdit10.Left = 858
            self.LabeledEdit10.Top = 115
            self.LabeledEdit10.Width = 128
            self.LabeledEdit10.Height = 23
            self.LabeledEdit10.Cursor = crArrow
            self.LabeledEdit10.EditLabel.Width = 129
            self.LabeledEdit10.EditLabel.Height = 15
            self.LabeledEdit10.EditLabel.Caption = 'Pedal Min Position(mm)'
            self.LabeledEdit10.TabOrder = 11
            self.LabeledEdit10.Text = 'LabeledEdit5'
            # Create control: Button4 = Button(self)
            self.Button4 = Button(self)
            self.Button4.Name = "Button4"
            self.Button4.Parent = self.pnlCenter
            self.Button4.Left = 717
            self.Button4.Top = 186
            self.Button4.Width = 141
            self.Button4.Height = 32
            self.Button4.Cursor = crArrow
            self.Button4.Caption = 'Set Pedal Range'
            self.Button4.ImageIndex = 20
            self.Button4.Images = app.get_system_imagelist_16px()
            self.Button4.TabOrder = 12
            # Create control: Panel11 = Panel(self)
            self.Panel11 = Panel(self)
            self.Panel11.Name = "Panel11"
            self.Panel11.Parent = self.pnlGround
            self.Panel11.Left = 1
            self.Panel11.Top = 294
            self.Panel11.Width = 996
            self.Panel11.Height = 207
            self.Panel11.Cursor = crArrow
            self.Panel11.Align = "alClient"
            self.Panel11.Caption = 'Panel11'
            self.Panel11.ShowCaption = "False"
            self.Panel11.TabOrder = 2
            # Create control: Label1 = Label(self)
            self.Label1 = Label(self)
            self.Label1.Name = "Label1"
            self.Label1.Parent = self.Panel11
            self.Label1.Left = 19
            self.Label1.Top = 32
            self.Label1.Width = 134
            self.Label1.Height = 15
            self.Label1.Cursor = crArrow
            self.Label1.Caption = 'Table Position to Pressure'
            # Create control: Label2 = Label(self)
            self.Label2 = Label(self)
            self.Label2.Name = "Label2"
            self.Label2.Parent = self.Panel11
            self.Label2.Left = 19
            self.Label2.Top = 128
            self.Label2.Width = 120
            self.Label2.Height = 15
            self.Label2.Cursor = crArrow
            self.Label2.Caption = 'Table Pressure to Force'
            # Create control: Button5 = Button(self)
            self.Button5 = Button(self)
            self.Button5.Name = "Button5"
            self.Button5.Parent = self.Panel11
            self.Button5.Left = 474
            self.Button5.Top = 19
            self.Button5.Width = 192
            self.Button5.Height = 32
            self.Button5.Cursor = crArrow
            self.Button5.Caption = 'Excute Position Calibration'
            self.Button5.ImageIndex = 20
            self.Button5.Images = app.get_system_imagelist_16px()
            self.Button5.TabOrder = 0
            # Create control: StringGrid1 = StringGrid(self)
            self.StringGrid1 = StringGrid(self)
            self.StringGrid1.Name = "StringGrid1"
            self.StringGrid1.Parent = self.Panel11
            self.StringGrid1.Left = 19
            self.StringGrid1.Top = 58
            self.StringGrid1.Width = 653
            self.StringGrid1.Height = 51
            self.StringGrid1.Cursor = crArrow
            self.StringGrid1.ColCount = 10
            self.StringGrid1.RowCount = 2
            self.StringGrid1.ScrollBars = "ssNone"
            self.StringGrid1.TabOrder = 1
            # Create control: Button6 = Button(self)
            self.Button6 = Button(self)
            self.Button6.Name = "Button6"
            self.Button6.Parent = self.Panel11
            self.Button6.Left = 256
            self.Button6.Top = 19
            self.Button6.Width = 179
            self.Button6.Height = 32
            self.Button6.Cursor = crArrow
            self.Button6.Caption = 'Apply New Value'
            self.Button6.ImageIndex = 20
            self.Button6.Images = app.get_system_imagelist_16px()
            self.Button6.TabOrder = 2
            # Create control: Button7 = Button(self)
            self.Button7 = Button(self)
            self.Button7.Name = "Button7"
            self.Button7.Parent = self.Panel11
            self.Button7.Left = 474
            self.Button7.Top = 115
            self.Button7.Width = 198
            self.Button7.Height = 32
            self.Button7.Cursor = crArrow
            self.Button7.Caption = 'Enable Force Calibration'
            self.Button7.ImageIndex = 20
            self.Button7.Images = app.get_system_imagelist_16px()
            self.Button7.TabOrder = 3
            # Create control: StringGrid2 = StringGrid(self)
            self.StringGrid2 = StringGrid(self)
            self.StringGrid2.Name = "StringGrid2"
            self.StringGrid2.Parent = self.Panel11
            self.StringGrid2.Left = 19
            self.StringGrid2.Top = 147
            self.StringGrid2.Width = 653
            self.StringGrid2.Height = 51
            self.StringGrid2.Cursor = crArrow
            self.StringGrid2.ColCount = 10
            self.StringGrid2.RowCount = 2
            self.StringGrid2.ScrollBars = "ssNone"
            self.StringGrid2.TabOrder = 4
        finally:
            # End UI auto creation
            self.EndUIAutoCreation()
# Auto Generated Python Code, do not modify END [UI] ----------------
        # your init code starts here...
        
# Auto Generated Python Code, do not modify START [MAIN] ------------
if __name__ == "__main__":
    try:
        Pedal_Control().Show()
        Application.Run()
    except SystemExit:
        pass
# Auto Generated Python Code, do not modify END [MAIN] --------------
